language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2

env:
    global:
        secure: "BpapBCTyt8h4B83jUGjH+W6WoOVI9f1x5MzsUl5GhMNgbObWXCLipbnJM6MpBCyz6FxP7VO2HzRRtr5mFFfkHfYTuiloYH6nfuvhsd1f+AsxIXiW8VXeCaCJuXHD/8B2epSkeC1EnlEndpeqLgTPFA4bNSH1nrdhqNRwQP6626/N5SWKsnkPsNQpgfkH4H0x7nc5R+k68rMmaU9mHS6fYRW9lJBwFTERIzRAtyc2QVnJH7/SbJW0FNHxWZbxXZ3jdXwwNllJQ1zfttfSsz4zX9H4sqnr39WBNBTh6xnait/O3Ww4g/H/l1cW87tTjU0IH1n5GTbSvKOFcp2vTeNaxsNlPRvophR1SJsi6Gnfs1wRLBlAOHAfQKg3Zj62JUqUqrHt25JwHrutKIsxURi1fZigffEy6lphUu81Ne4uSIXFa24VFpac/iZQ8gTYEo6XWXSZltjk6yS58bNFpw5eflonD7+34SYrrRWJbO2KkjSLOviBrYen2hLdPxjN35sZMjnZikCbSA0T3Ye3VUw4P63r66T1LDkJPOxTwHVPIVFDqR/HmZkg8A4qWsxx1e7DNQlqfsYov+10uaUO4hxG1YiJNQb2HWUezUbbDSIy3yb3mKqpyZWbuvIExQLEmhd/rOhk750Q1WhtfRzAq+Q1cNQfBLIo1gKSKqECWEWsliA="
        secure: "F0wntKS4kTDK6OXy3FzT81owFaWi1TCxoyVgoSwhxqUEfEM+UnkG0ae6gPjneD/mzhdxRhBIaKfchLjI5xXO8Q/Qt9J1IXT3nXccFrNm4Hp3yur/Ux/eIyDnQf9MnT8mhFeO6qpEQ2IEXFvEf/+URHpAASUhZq/ywfm6Gj41wjD3HEpRKLMWo6AChxZvI2FxNZVC9Kk40259jO+eIAcScVpOpMnljZeKNjM84UoIspuAvuy0iK2TPfIznIrWhlu2jrLcu07oc8BclylqhFVP/PTSw+nqpzN6veejAPlF7cZwlwDBThOP7UUpLIRNoGXaJS4uanE7bxBLhXoB/qP8xGg00Xs+/bEptV+LKSZmzf4M2lWE/a6sExyWzotI3ZJtq7Vryi7dqefYUzKj7Q6vKXy/P/1A0yFMExsh8NXuAz/t/dvu3LvYZjQe8FFhlLnqeX0OwMus9usRQZp2dapa51xERkY5PAADa5jtLTwunJCZ8UkKWzdWRGm/fturkwOwt2BjlV6aJemEgAFDQ7JTfHH+xVT0BOOGGKFRmQaUZ8ePYrZOIwa32HRwx9veoGlQLUY9RGCcEIjxbSJnji3IdBVU00sQ3Gk6aArnY8t/8Oa8zHDedqHjrfdB0P/zpYtyrktuIR0CsEnjwGOswBsHmiXPE+XJwHAmKFzaargIJjs="
        secure: "CEciW8Se7zfveMA3Ngq0b/rMZbedNs65x/Y56G2FAT5Z4j85QKVSJk1sH7mgSdSHB8sfeGD7WWEFifp2ipf5x1/MjKK0XBfryX/OVPGfgCCr7nsdXoF23nAYVJEe3pyeCYmwG1idGNhrVoFVCwKLJZ8h71TsN6OjbddeaImNBo2sSIfW1jA69GYjoC3tDG++eIZtwgrNh16kFnlxErNOE/Kc3dfQenOhYqmtI/yYADA4Xlsg9jVAqsfcI/WFaFQA5uikz2I0UZ0ET67LWl8A1KnzKLn6eCSlnEAIdQlvHQdRPvTijk1j0cv3+YC+to2Y0pXAehD7lT/9zsWU52j32CCnldwtSOrrHX0VOoo8S0qdLG5pSDYRF60r68cNN1E3ze3qSiE07jAlgpAwTywWff3Fysj5Gmi83oqXlJhCuFcpwf5FpLR1IAEJgg/s58jxc1wK8vOv+PiGJ+9biiCoFfBR2oyK+giAdAipsN9zh2qI2N9scHcz/qk4Kazzy6UyP4HABVXGTUbja+tkkLoMZvO6WEezWw+IMTm0J/ZSpkZaOIC+GDbqPCR1TALOW47HJakwfROQQ4TMTtx8ES7AUeGY7PS1mQCyiorH9D+Q6QneyNPe9GdJIlRUw3vx1TpsJ+HZxNnGMpadnBgTYsGLAat61Da3loBY9wDpeLmcRYQ="

addons:
  code_climate:
    repo_token:
        secure: "RnnIrzTkNYZn5ocWr8dIenHBFk/cwzF4AUvgHMZQlsHtgFclIX204xMEHL0bF+DR1XJNYqNE7Dk7Oqt1bt62ht7eTmOsOKhxcoDirbjp1We0o24ZyRIoso9qUg4YoDlc0K+QPx/u6OZHRkLny2+BHKPpLDV3MMSBo+n8MZJ1WiVqBpuHmlT3WV4kfeBpZoLDxbfVfFlczP27BV9M6anlT6ntsdR6HmqHruFQKvN+ulH5VFbBrQEEHsq/+zpcepS6rumoDhvD2BxjHGV046/GQSEiAcCEwsmgeSFilz2QqVXEx/xlJVqwCSxoih63e7uBfEgRPTuQ3CEsKVhnPzy1T72xqRsHOoYpQO//nXSER5LFlW7Sul2W1Zvzbco6LKQ4RXrdVzh3olCzBo8Ze4nkiHdsdUHkK0mM9ckR3WWWbFpmK0R4eACwzrpZC+7GUZmG+Xzipa716Bx9kT3XtOzlzOSWRlsLDlBML9LnkK6V1QOhgeotl6QqXcTWxnzPB9Dbjm0gF0Tpv+DSn9zRMvR2P1eKr7JFGiy4/FZ0W0aMd1HZPYRI7vwBHABRx2sgo7p5QFEoP/VmC73qRBVmCemPbF4R9hp0hhGrV7HHfb2DL1NjagkHdPDAIteHXpDc37EyP6ZH2JS/svCXTjq9HlpOnWaT85mq6EQxHZi7Xva46QY="

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer update --no-scripts

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always