language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2

env:
    global:
        secure: "A48ClMyawNKGiVWM8IbMrNbhk7zM1Wxq/y2ByRI0p752jtHVsGPqDMfxOYsJAWDp+VLMp5LRP/cJlzpevxOo4nznza1r3xRoT0B1+qbkJsypcKN+J4lQx2SRAxRgMKWQBgwqEnYX0UqBMxQ3aom2xusQPmfg3QBBCcvFJFGN9T6dS9asB0/UXf2bBlqd/j+4SH8kExuvvOEF3DEo5Jo8mnjPmcujeUaGmGLONSrzCtIi2TKEunM13hnhfzqRg0yVqgxBjcOLoH3CI/KiP4QMZAv+an+S/tC4jcDfvweuNaPzZ+J1G+Lu/s00c46HpW+ol8aWe3mQbRYpJ6t30GhPDKR+MqhxV2m0hqR355a3DUmHOl11kmYvTf7tIG4j6m6mFUwKN/yezqOp3KhBEGjfLAYQOG4flBRPsdean4Q+oOgQknz+7V2/Msb3OlbVH1HCiNSV6QbB3UC9DkfQJkOXDN0Wj1GnEUG60sgQuWbo5LGXvVoekt2nI+0CukXTOmUNhH2Nu6u+D/hmvEDQYToFSACoHj+hOWUP6co69CyE40nWYFicaM81JyoT4SyEWcw8T3nQnJP+rD1A3zTOARlJshVemJHD06gIwnbGskWYVyrPqmYCsL3vFHGFVQ14NRuvgzjoYfW/s8MJ3mQ5Zpqv9XgM3WcBwC0M+R5QTqCFalA="

addons:
  code_climate:
    repo_token:
        secure: "RnnIrzTkNYZn5ocWr8dIenHBFk/cwzF4AUvgHMZQlsHtgFclIX204xMEHL0bF+DR1XJNYqNE7Dk7Oqt1bt62ht7eTmOsOKhxcoDirbjp1We0o24ZyRIoso9qUg4YoDlc0K+QPx/u6OZHRkLny2+BHKPpLDV3MMSBo+n8MZJ1WiVqBpuHmlT3WV4kfeBpZoLDxbfVfFlczP27BV9M6anlT6ntsdR6HmqHruFQKvN+ulH5VFbBrQEEHsq/+zpcepS6rumoDhvD2BxjHGV046/GQSEiAcCEwsmgeSFilz2QqVXEx/xlJVqwCSxoih63e7uBfEgRPTuQ3CEsKVhnPzy1T72xqRsHOoYpQO//nXSER5LFlW7Sul2W1Zvzbco6LKQ4RXrdVzh3olCzBo8Ze4nkiHdsdUHkK0mM9ckR3WWWbFpmK0R4eACwzrpZC+7GUZmG+Xzipa716Bx9kT3XtOzlzOSWRlsLDlBML9LnkK6V1QOhgeotl6QqXcTWxnzPB9Dbjm0gF0Tpv+DSn9zRMvR2P1eKr7JFGiy4/FZ0W0aMd1HZPYRI7vwBHABRx2sgo7p5QFEoP/VmC73qRBVmCemPbF4R9hp0hhGrV7HHfb2DL1NjagkHdPDAIteHXpDc37EyP6ZH2JS/svCXTjq9HlpOnWaT85mq6EQxHZi7Xva46QY="

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer update --no-scripts

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always