language: php
sudo: true
php:
  - 5.6
  - 7.1

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | 
  - sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  - cp .env.travis .env
  - mysql -e 'create database square_test;'
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit -c phpunit.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always